### ISSUE TITLE
toncli deploy -n testnet -wc 0  Error

### ISSUE THREAD

**Issue by IcarusRyy** [disintar/toncli#50]
PS D:\demo\TonDemo-next\wallet> toncli deploy -n testnet -wc 0
INFO: 🚀 You want to interact with your contracts ['contract'] in testnet - that's great!
Traceback (most recent call last):
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\Scripts\toncli.exe\__main__.py", line 7, in <module>
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\main.py", line 60, in main
    CommandsExecuter(command, string_kwargs, parser)
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\utils\commands\commands_executer.py", line 40, in __init__
    self.command_mapper[command](self)
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\utils\commands\commands_executer.py", line 71, in deploy_command
    return DeployCommand(self.string_kwargs, self.parser)
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\utils\commands\command_classes\deploy_command.py", line 12, in __init__
    deployer = ContractDeployer(network=args.net, update_config=args.update,
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\deploy_contract.py", line 43, in __init__
    self.deploy_contract = DeployWalletContract(network, workchain)
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\deploy_wallet_contract.py", line 68, in __init__
    self.addresses = self.get_address()
  File "C:\Users\计算机\AppData\Local\Programs\Python\Python310\lib\site-packages\toncli\modules\abstract\deployer.py", line 126, in get_address
    raise ValueError(f"😥 No address_text found in {contract.address}")
ValueError: 😥 No address_text found in C:\Users\计算机\AppData\Local\toncli\toncli\wallet/build/contract_address

**Comment by KuznetsovNikita** [comment]
@IcarusRyy testnet was updated service addresses
new config is here - https://ton-blockchain.github.io/testnet-global.config.json

**Comment by KuznetsovNikita** [comment]
Maybe it's because wrong testnet config file
Here is a new one - https://ton-blockchain.github.io/testnet-global.config.json

**Comment by nickerlan** [comment]
I'm using MacOS Monterey.
Fixed this issue by adding fift libs directory content from `ton/crypto/fift/lib` to `toncli/src/toncli/modules/fift`
