### ISSUE TITLE
Error with toncli send --mode 64

### ISSUE THREAD

**Issue by serhiibeznisko** [disintar/toncli#52]
I got a type error when I try to send a simple message with --mode specified. Without the mode flag the command works fine.

`toncli send -a 0.1 --mode 64 --net testnet`

Logs:
```
INFO: 🚀 You want to interact with your contracts ['contract'] in testnet - that's great!
INFO: 🦘 Found existing deploy-wallet [address] (Balance: 1.390550483💎, Is inited: True) in /Users/user/Library/Application Support/toncli
INFO: 🤔 You want to send internal message to [contract] from deploy-wallet with amount [0.1]
INFO: 🐰 Getting seqno for transaction
Traceback (most recent call last):
  File "/opt/homebrew/bin/toncli", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/toncli/main.py", line 60, in main
    CommandsExecuter(command, string_kwargs, parser)
  File "/opt/homebrew/lib/python3.9/site-packages/toncli/modules/utils/commands/commands_executer.py", line 40, in __init__
    self.command_mapper[command](self)
  File "/opt/homebrew/lib/python3.9/site-packages/toncli/modules/utils/commands/commands_executer.py", line 56, in send_command
    return SendCommand(self.string_kwargs, self.parser)
  File "/opt/homebrew/lib/python3.9/site-packages/toncli/modules/utils/commands/command_classes/send_command.py", line 25, in __init__
    deployer.send([], args)
  File "/opt/homebrew/lib/python3.9/site-packages/toncli/modules/abstract/deployer.py", line 267, in send
    logger.info(f"Run command: {' '.join(args)}")
TypeError: sequence item 7: expected str instance, int found
```

My toncli version is 0.0.37

**Comment by tvorogme** [comment]
Will check it out

**Comment by nickerlan** [comment]
Wrote quick fix here. 
#50
